#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# Path to the current BSP
SEARCH_TARGET_APP_RAK_GAN=bsps/TARGET_APP_RAK_GAN

# The search paths for the included middleware
SEARCH_cmsis=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cmsis/release-v6.1.0
SEARCH_core-lib=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-lib/release-v1.7.0
SEARCH_core-make=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-make/release-v3.9.0
SEARCH_lvgl=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/lvgl/v8.3.5
SEARCH_mtb-hal-psc3=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-hal-psc3/release-v1.1.2
SEARCH_mtb-pdl-cat1=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-pdl-cat1/release-v3.21.1
SEARCH_mtb-pwrconv=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-pwrconv/release-v2.0.0
SEARCH_recipe-make-cat1b=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/recipe-make-cat1b/release-v2.8.2
SEARCH_retarget-io=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/retarget-io/release-v1.9.0
SEARCH_syspm-callbacks-psc3=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/syspm-callbacks-psc3/release-v1.1.0

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_lvgl)
SEARCH_MTB_MK+=$(SEARCH_mtb-hal-psc3)
SEARCH_MTB_MK+=$(SEARCH_mtb-pdl-cat1)
SEARCH_MTB_MK+=$(SEARCH_mtb-pwrconv)
SEARCH_MTB_MK+=$(SEARCH_recipe-make-cat1b)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_syspm-callbacks-psc3)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_LVGL
COMPONENTS += MW_MTB_HAL_PSC3
COMPONENTS += MW_MTB_PDL_CAT1
COMPONENTS += MW_MTB_PWRCONV
COMPONENTS += MW_RECIPE_MAKE_CAT1B
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_SYSPM_CALLBACKS_PSC3

# Register map file
DEVICE_PSC3M5FDS2AFQ1_SVD=$(SEARCH_mtb-pdl-cat1)/devices/COMPONENT_CAT1B/svd/psc3.svd


#
# generate make targets for the graphical editors that are specific to this project
#

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

CY_HELP_bsp-assistant=Launches the BSP Assistant 1.70 GUI
CY_HELP_bsp-assistant_VERBOSE=Launches the BSP Assistant 1.70 GUI. Check the BSP Assistant 1.70 User Guide for more information.
mtb_help_tool_bsp-assistant:
	@:
	$(info $(MTB__SPACE)bsp-assistant       $(CY_HELP_bsp-assistant))

mtb_help_tools_end: mtb_help_tool_bsp-assistant
mtb_help_tool_bsp-assistant: mtb_help_tools_start
.PHONY: mtb_help_tool_bsp-assistant

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

CY_HELP_config=Launches the Device Configurator 5.70 GUI for the target's modus file
CY_HELP_config_VERBOSE=Launches the Device Configurator 5.70 GUI. Check the Device Configurator 5.70 User Guide for more information.
mtb_help_tool_config:
	@:
	$(info $(MTB__SPACE)config              $(CY_HELP_config))

mtb_help_tools_end: mtb_help_tool_config
mtb_help_tool_config: mtb_help_tools_start
.PHONY: mtb_help_tool_config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

CY_HELP_device-configurator=Launches the Device Configurator 5.70 GUI for the target's modus file
CY_HELP_device-configurator_VERBOSE=Launches the Device Configurator 5.70 GUI. Check the Device Configurator 5.70 User Guide for more information.
mtb_help_tool_device-configurator:
	@:
	$(info $(MTB__SPACE)device-configurator $(CY_HELP_device-configurator))

mtb_help_tools_end: mtb_help_tool_device-configurator
mtb_help_tool_device-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_device-configurator

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

CY_HELP_modlibs=Launches the Library Manager 2.70 GUI
CY_HELP_modlibs_VERBOSE=Launches the Library Manager 2.70 GUI. Check the Library Manager 2.70 User Guide for more information.
mtb_help_tool_modlibs:
	@:
	$(info $(MTB__SPACE)modlibs             $(CY_HELP_modlibs))

mtb_help_tools_end: mtb_help_tool_modlibs
mtb_help_tool_modlibs: mtb_help_tools_start
.PHONY: mtb_help_tool_modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

CY_HELP_library-manager=Launches the Library Manager 2.70 GUI
CY_HELP_library-manager_VERBOSE=Launches the Library Manager 2.70 GUI. Check the Library Manager 2.70 User Guide for more information.
mtb_help_tool_library-manager:
	@:
	$(info $(MTB__SPACE)library-manager     $(CY_HELP_library-manager))

mtb_help_tools_end: mtb_help_tool_library-manager
mtb_help_tool_library-manager: mtb_help_tools_start
.PHONY: mtb_help_tool_library-manager

smartio-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name smartio-configurator
.PHONY: smartio-configurator

CY_HELP_smartio-configurator=Launches the Smart I/O Configurator 4.70 GUI for the target's modus file
CY_HELP_smartio-configurator_VERBOSE=Launches the Smart I/O Configurator 4.70 GUI. Check the Smart I/O Configurator 4.70 User Guide for more information.
mtb_help_tool_smartio-configurator:
	@:
	$(info $(MTB__SPACE)smartio-configurator $(CY_HELP_smartio-configurator))

mtb_help_tools_end: mtb_help_tool_smartio-configurator
mtb_help_tool_smartio-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_smartio-configurator

power-conversion-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name power-conversion-configurator
.PHONY: power-conversion-configurator

CY_HELP_power-conversion-configurator=Launches the Power Conversion Configurator 1.1 GUI for the target's modus file
CY_HELP_power-conversion-configurator_VERBOSE=Launches the Power Conversion Configurator 1.1 GUI. Check the Power Conversion Configurator 1.1 User Guide for more information.
mtb_help_tool_power-conversion-configurator:
	@:
	$(info $(MTB__SPACE)power-conversion-configurator $(CY_HELP_power-conversion-configurator))

mtb_help_tools_end: mtb_help_tool_power-conversion-configurator
mtb_help_tool_power-conversion-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_power-conversion-configurator

.PHONY: mtb_help_tools_start mtb_help_tools_end
